<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-02-27 12:25
=======
# Generated by Django 4.2.10 on 2024-02-27 12:43
>>>>>>> fd3af8edf410c39a17bc7265d893d5eda12e82d9

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('sede_local', models.CharField(max_length=150)),
                ('telefone_contato', models.BigIntegerField()),
                ('entrada_data', models.DateTimeField(verbose_name='Data publicada')),
            ],
        ),
        migrations.CreateModel(
>>>>>>> fd3af8edf410c39a17bc7265d893d5eda12e82d9
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Para o preço, não esqueça dos centavos! Exemplo: 10.99', max_digits=5)),
                ('quantidade', models.IntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('tamanho', models.CharField(max_length=10)),
<<<<<<< HEAD
=======
                ('alerta_estoque', models.IntegerField()),
>>>>>>> fd3af8edf410c39a17bc7265d893d5eda12e82d9
            ],
        ),
    ]
