# Generated by Django 5.0.2 on 2024-02-27 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Para o preço, não esqueça dos centavos! Exemplo: 10.99', max_digits=5)),
                ('quantidade', models.IntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('tamanho', models.CharField(max_length=10)),
            ],
        ),
    ]
