# Generated by Django 4.2.10 on 2024-02-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controleestoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ('categoria',),
            },
        ),
        migrations.AddField(
            model_name='produtos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controleestoque.categoria'),
        ),
    ]
